version: '3.9'
services:
  web:
    container_name: forum
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    networks:
      - db_default
networks:
  db_default:
    external: true