ALTER TABLE `advertisements` ADD `type` INT NOT NULL DEFAULT '1' AFTER `status`, ADD `script` TEXT NULL DEFAULT NULL AFTER `type`;
ALTER TABLE `advertisements` CHANGE `url` `url` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL, CHANGE `image` `image` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL;
ALTER TABLE `posts` ADD `image` VARCHAR(191) NULL DEFAULT NULL AFTER `status`;
ALTER TABLE `posts` ADD `video` VARCHAR(191) NULL DEFAULT NULL AFTER `image`;